// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnFTTGL0PnDGIuvnX-tyu2zkZwRYfXvJk',
    appId: '1:527556314299:android:cf019b6043122566b5559e',
    messagingSenderId: '527556314299',
    projectId: 'suplleex-sherif',
    databaseURL: 'https://suplleex-sherif-default-rtdb.firebaseio.com',
    storageBucket: 'suplleex-sherif.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlybYvYB1M16LGJzvxqX7qaXUXVC-2DuE',
    appId: '1:527556314299:ios:85993f86fa5393bfb5559e',
    messagingSenderId: '527556314299',
    projectId: 'suplleex-sherif',
    databaseURL: 'https://suplleex-sherif-default-rtdb.firebaseio.com',
    storageBucket: 'suplleex-sherif.firebasestorage.app',
    androidClientId: '527556314299-7c0voe4a8g1rp766qt1oc8kkl9scm4h0.apps.googleusercontent.com',
    iosClientId: '527556314299-mgfc5or2c468k5blbqaa7lcl6m6c09ec.apps.googleusercontent.com',
    iosBundleId: 'com.all.safe',
  );
}
