// lib/common/helper/apple_pay_troubleshooter.dart
import 'dart:io';
import 'package:bubbly/common/manager/logger.dart';
import 'package:bubbly/common/service/email_service.dart';

class ApplePayTroubleshooter {
  static const String kExpectedMerchantId = "merchant.com.all.safe";

  /// Diagnose Apple Pay loading/presentation issues
  static Future<ApplePayDiagnosisResult> diagnoseLoadingIssue({
    String? userId,
    String? userEmail,
    Map<String, dynamic>? paymentConfig,
  }) async {
    final result = ApplePayDiagnosisResult();
    final issues = <String>[];
    final recommendations = <String>[];

    try {
      // 1. Platform Check
      if (!Platform.isIOS) {
        issues.add("❌ Not running on iOS - Apple Pay requires iOS device");
        recommendations.add("Test on physical iOS device, not simulator");
        result.severity = DiagnosisSeverity.critical;
      }

      // 2. Configuration Validation
      if (paymentConfig != null) {
        if (paymentConfig['profileId']?.toString().isEmpty ?? true) {
          issues.add("❌ PayTabs Profile ID is missing or empty");
          recommendations.add("Check PayTabs API response for profile_id");
          result.severity = DiagnosisSeverity.critical;
        }

        if (paymentConfig['serverKey']?.toString().isEmpty ?? true) {
          issues.add("❌ PayTabs Server Key is missing or empty");
          recommendations.add("Verify PayTabs server configuration");
          result.severity = DiagnosisSeverity.critical;
        }

        if (paymentConfig['clientKey']?.toString().isEmpty ?? true) {
          issues.add("❌ PayTabs Client Key is missing or empty");
          recommendations.add("Check PayTabs client key configuration");
          result.severity = DiagnosisSeverity.critical;
        }

        if (paymentConfig['cartId']?.toString().isEmpty ?? true) {
          issues.add("❌ Cart ID is missing or empty");
          recommendations.add("Ensure cart_id is generated by PayTabs API");
          result.severity = DiagnosisSeverity.critical;
        }

        final amount = paymentConfig['amount'] as double?;
        if (amount == null || amount <= 0) {
          issues.add("❌ Invalid payment amount: $amount");
          recommendations.add("Verify coin package price is greater than 0");
          result.severity = DiagnosisSeverity.critical;
        }
      }

      // 3. Merchant ID Validation
      final merchantId = paymentConfig?['merchantId']?.toString() ?? kExpectedMerchantId;
      if (!merchantId.startsWith('merchant.')) {
        issues.add("❌ Invalid Merchant ID format: $merchantId");
        recommendations.add("Merchant ID must start with 'merchant.' prefix");
        result.severity = DiagnosisSeverity.critical;
      }

      if (merchantId != kExpectedMerchantId) {
        issues.add("⚠️ Merchant ID mismatch: configured=$merchantId, expected=$kExpectedMerchantId");
        recommendations.add("Update Merchant ID to match Apple Developer Console");
        if (result.severity == DiagnosisSeverity.none) {
          result.severity = DiagnosisSeverity.warning;
        }
      }

      // 4. Common Apple Pay Issues
      if (issues.isEmpty) {
        // If no configuration issues, check common Apple Pay problems
        issues.add("⚠️ Apple Pay sheet not appearing - possible causes:");
        issues.add("  • Apple Pay not set up on device");
        issues.add("  • No payment cards added to Apple Pay");
        issues.add("  • Merchant ID not configured in iOS entitlements");
        issues.add("  • PayTabs simplifyApplePayValidation setting");
        issues.add("  • Network connectivity issues");

        recommendations.addAll([
          "1. Check device Settings → Wallet & Apple Pay",
          "2. Ensure at least one card is added to Apple Pay",
          "3. Verify iOS app entitlements include correct Merchant ID",
          "4. Set simplifyApplePayValidation to false in PayTabs config",
          "5. Test with different payment amounts",
          "6. Check network connectivity",
          "7. Test on different iOS device if available",
        ]);

        if (result.severity == DiagnosisSeverity.none) {
          result.severity = DiagnosisSeverity.warning;
        }
      }

      result.issues = issues;
      result.recommendations = recommendations;
      result.timestamp = DateTime.now();

      // Send diagnosis report via email
      await _sendDiagnosisReport(result, userId, userEmail, paymentConfig);

      return result;

    } catch (e, st) {
      Loggers.error('Apple Pay diagnosis failed: $e');
      result.severity = DiagnosisSeverity.critical;
      result.issues.add('Diagnosis process failed: ${e.toString()}');
      return result;
    }
  }

  /// Send diagnosis report via email
  static Future<void> _sendDiagnosisReport(
      ApplePayDiagnosisResult result,
      String? userId,
      String? userEmail,
      Map<String, dynamic>? paymentConfig,
      ) async {
    try {
      final emailService = EmailService();

      final errorDetails = {
        'diagnosis': {
          'severity': result.severity.toString(),
          'issues': result.issues,
          'recommendations': result.recommendations,
          'timestamp': result.timestamp.toIso8601String(),
        },
        'paymentConfiguration': paymentConfig ?? {},
        'deviceInfo': {
          'platform': Platform.operatingSystem,
          'version': Platform.operatingSystemVersion,
          'isIOS': Platform.isIOS,
        },
        'troubleshooting': {
          'commonCauses': [
            'Apple Pay not set up on device',
            'No payment cards in Apple Pay',
            'Merchant ID configuration issues',
            'PayTabs integration problems',
            'iOS entitlements missing',
            'Network connectivity issues',
          ],
          'immediateActions': [
            'Check device Apple Pay setup',
            'Verify payment cards are added',
            'Review Merchant ID configuration',
            'Test network connectivity',
            'Check iOS app entitlements',
          ],
        },
      };

      await emailService.sendApplePayErrorReport(
        errorCode: 'APPLE_PAY_LOADING_ISSUE',
        errorMessage: 'Apple Pay loading/presentation diagnosis',
        errorDetails: errorDetails,
        userEmail: userEmail,
        userId: userId,
      );
    } catch (e) {
      Loggers.error('Failed to send diagnosis report: $e');
    }
  }

  /// Quick check for common Apple Pay issues
  static List<String> getQuickDiagnosisSteps() {
    return [
      "1. 📱 Check if running on physical iOS device (not simulator)",
      "2. ⚙️ Go to Settings → Wallet & Apple Pay",
      "3. 💳 Verify at least one payment card is added",
      "4. 🔧 Check iOS app entitlements for Merchant ID",
      "5. 🌐 Test network connectivity",
      "6. 🔄 Try different payment amount",
      "7. 📧 Check email for detailed error reports",
    ];
  }

  /// Get Apple Pay setup instructions
  static List<String> getApplePaySetupInstructions() {
    return [
      "📱 Apple Pay Setup Instructions:",
      "",
      "1. Open Settings app on iOS device",
      "2. Tap 'Wallet & Apple Pay'",
      "3. Tap 'Add Card' or '+' button",
      "4. Follow instructions to add credit/debit card",
      "5. Verify card with bank if required",
      "6. Set default card if multiple cards added",
      "7. Enable 'Allow Payments on Mac' if needed",
      "",
      "🏪 Merchant Configuration:",
      "1. Verify Merchant ID in Apple Developer Console",
      "2. Check iOS app entitlements file",
      "3. Ensure PayTabs configuration is correct",
      "4. Test with small amounts first",
    ];
  }
}

enum DiagnosisSeverity {
  none,
  warning,
  critical,
}

class ApplePayDiagnosisResult {
  DiagnosisSeverity severity = DiagnosisSeverity.none;
  List<String> issues = [];
  List<String> recommendations = [];
  DateTime timestamp = DateTime.now();

  Map<String, dynamic> toJson() => {
    'severity': severity.toString(),
    'issues': issues,
    'recommendations': recommendations,
    'timestamp': timestamp.toIso8601String(),
  };

  @override
  String toString() => 'ApplePayDiagnosisResult(severity: $severity, issues: ${issues.length}, recommendations: ${recommendations.length})';
}
